### ISSUE TITLE
Missing script disable in 2.1.1

### ISSUE THREAD

**Issue by ungear** [vaadin/vaadin-usage-statistics#52] opened 2022-01-26 13:14 UTC
In npm package version 2.1.1 there is no **disable** script in **package.json**. As a result, opting out via command `npm explore @vaadin/vaadin-usage-statistics -- npm run disable` fails with error `missing script: disable`

**Comment by web-padawan** [comment] 2022-01-26 14:26
Thanks for the issue. It's caused by incorrect update of our Polymer 3 conversion utility. I will work on a fix.

**Comment by web-padawan** [comment] 2022-01-27 10:32
Fix is released in `v2.1.2`.

**Closed by web-padawan** 2022-01-27 10:32 UTC
